const en = {
    lang: 'en',
    firstName: "Gleb Glushchenko",
    working: "Working experiences",
    attainments: "Attainments",
    developer_1: "Frontend developer",
    developer_2: "Frontend developer",
    individual_1: "Individual-Entrepreneur:'MELDO'",
    individual_2: "OOO 'Roskvartal'",
    about_company: "Продуктовая компания, занимающаяся оказанием услуг в сфере ЖКХ. В команде разработчиков 10 человек, разрабатываем основные продукты для внутреннего и внешнего использования,а также для клиентов.",
    my__work_flow: "Я работаю над:",
    workSkills_1: "- Resolving domestic objectives",
    workSkills_2: "- Care of your system",
    workSkills_3: "- Development of new solutions",
    workSkills_4: "- Development of client applications and services",
    workSkills_5: "- Developing internal solutions for employees.",
    workSkills_6: "- Design and development of email newsletters.",
    workSkills_7: "- The working stack varies from React / Vue / Angular / Svelte to legacy.",
    workSkills_8: "- Working with git using the git flow methodology.",
    skillsTitle: "Other skills:",
    date_1: "May",
    date_2: "June",
    date_3: "June",
    date_4: "currently",
};

const ru = {
    lang: 'ru',
    firstName: "Глеб Глущенко",
    working: "Опыт",
    attainments: "Навыки",
    developer_1: "Frontend developer",
    developer_2: "Frontend developer",
    individual_1: "ИП МЕЛЬДО",
    individual_2: "ООО 'РосКвартал'",
    about_company: "Продуктовая компания, занимающаяся оказанием услуг в сфере ЖКХ. В команде разработчиков 10 человек, разрабатываем основные продукты для внутреннего и внешнего использования,а также для клиентов.",
    my__work_flow: "Я работаю над:",
    workSkills_1: "– разработкой новых компонентов и функционалом для внутренней системы CMS написанной на Angular и AngularJS",
    workSkills_2: "- Поддержка работы систем предприятия",
    workSkills_3: "- Разработка новых решений",
    workSkills_4: "– разработкой новых компонентов и функционалом для внутренней системы CMS написанной на Angular и AngularJS",
    workSkills_2: "- Поддержка работы систем предприятия",
    workSkills_5: "- Разработка внутренних решений для сотрудников",
    workSkills_6: "- Вёрстка и разработка Email-рассылок",
    workSkills_7: "- Рабочий стек варьируется от React / Vue / Angular / Svelte до legacy",
    workSkills_8: "- Работа с git flow",
    skillsTitle: "Другие скиллы:",
    date_1: "Май",
    date_2: "Июнь",
    date_3: "Июнь",
    date_4: "Н-В",
};
